spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/teamview
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect