spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/teamview?currentSchema=public
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    defer-datasource-initialization: true